#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

old_string="# SSL configuration"
new_string_file="new_string.txt"
file="/etc/nginx/sites-available/default"
cat > "$new_string_file" <<EOL
location /redirect_me {
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
EOL

sudo apt-get update
sudo apt install nginx
sudo sed -i "/$old_string/{
r $new_string_file
d
}" $file
sudo nginx -s reload
rm "$new_string_file"
