#!/usr/bin/env bash
# Bash script that:
# - Creates the file /var/run/myscript.pid containing its PID
# - Displays To infinity and beyond indefinitely
# - Displays I hate the kill command when receiving a SIGTERM signal
# - Displays Y U no love me?! when receiving a SIGINT signal
# - Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

mkdir var && mkdir var/run && touch var/run/myscript.pid

echo $!$BASHPID >> var/run/myscript.pid

trap "echo I hate the kill command" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm var/run/myscript.pid" SIGQUIT 
trap "rm var/run/myscript.pid" SIGTERM 

while true ; do
    echo "To infinity and beyond"
done