#!/usr/bin/env bash

count=1
while [ $count -le 20 ]; do
    echo $count
    case $count in
        4 )
            echo "bad luck from China" ;;
        8 )
            echo "bad luck from Japan" ;;
        17 )
            echo "bad luck from Italy"
    esac
    count=$(( count+1 ))
done