#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:
# - display hours from 0 to 12
# - display minutes from 1 to 59

hours=0
while [[ $hours -lt 12 ]]; do
    while [[ $minutes -le 60 ]]; do
        if [[ $minutes -eq 0 || $minutes -eq 60 ]]; then
            echo "Hour: $hours"
            hours=$((hours+1))
        else
            echo "$minutes"
        fi
        minutes=$((minutes+1))
    done
    minutes=1
done